// Code generated by gen_node_actions.go; DO NOT EDIT.

package app

var allNodeActions = [...]NodeActionMeta{
	{Tag: "AggregateAction", Alloc: func() NodeAction { return &AggregateAction{} }},
	{Tag: "ConcatTablesAction", Alloc: func() NodeAction { return &ConcatTablesAction{} }},
	{Tag: "LinesAction", Alloc: func() NodeAction { return &LinesAction{} }},
	{Tag: "ListFilesAction", Alloc: func() NodeAction { return &ListFilesAction{} }},
	{Tag: "LoadFileAction", Alloc: func() NodeAction { return &LoadFileAction{} }},
	{Tag: "RunProcessAction", Alloc: func() NodeAction { return &RunProcessAction{} }},
	{Tag: "SaveFileAction", Alloc: func() NodeAction { return &SaveFileAction{} }},
	{Tag: "TrimSpacesAction", Alloc: func() NodeAction { return &TrimSpacesAction{} }},
}

func (a *AggregateAction) Tag() string {
	return "AggregateAction"
}

func (a *ConcatTablesAction) Tag() string {
	return "ConcatTablesAction"
}

func (a *LinesAction) Tag() string {
	return "LinesAction"
}

func (a *ListFilesAction) Tag() string {
	return "ListFilesAction"
}

func (a *LoadFileAction) Tag() string {
	return "LoadFileAction"
}

func (a *RunProcessAction) Tag() string {
	return "RunProcessAction"
}

func (a *SaveFileAction) Tag() string {
	return "SaveFileAction"
}

func (a *TrimSpacesAction) Tag() string {
	return "TrimSpacesAction"
}
